### PR TITLE
Less invasive Improvements

### PR DESCRIPTION
**Pull request by juliomrqz**
These updates don't change the current Python logic, they just:

- Apply some recommendations from cookiecutter-djangopackage
- Add support for Django 1.10
- Fix some flake8 warnings
- Configure isort
- Fix the indentation of the example codes in **README.rst** and add the _Requirements_ section
- Configure Tox and Travis

### CODE REVIEW

**Comment by juliomrqz** [comment]
@rparent The created field was just added

**Comment by rparent** [comment]
@juliomrqz I just made some slight changes to the PR:
- Removed useless `manage.py` file
- Fixed API tests to make it pass with python 3
- Removed Django 1.7 and added Django 1.11 to the tox test grid. You were right, let's only support Django from 1.8 as it is LTS.

If you are OK with those changes, just add your name to the `CONTRIBUTORS.md` file and I will merge the PR.

**Comment by juliomrqz** [comment]
Those changes are perfect. I don't see the `CONTRIBUTORS.md` file.

**Comment by rparent** [comment]
Sorry I was referring to the AUTHORS.md file you just added with this PR.

**Comment by juliomrqz** [comment]
Perfect. I just updated the `AUTHORS.rst` file.

**Comment by rparent** [comment]
@juliomrqz New release including those changes available on Pypi. Thanks

**Pull request merged**
