### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by juliomrqz**
Hello. These updates include the following:

- Add support for Django 1.10
- Add fields created and modified to the LockToken Model using **django-model-utils** 
- Fix some flake8 warnings
- Use **Django Braces** in the API views
- Add support for tox and Travis

If you don't have time for maintaining this package, we can do it pleasantly without any problem.

### CODE REVIEW

**Comment by alexislg2** [comment]
Looks great! When will you merge?

**Comment by rparent** [comment]
Hello @juliomrqz, thanks for the PR!
I will have a look ASAP (quite dense and covers a lot of issues, not very easy to review).

**Comment by rparent** [comment]
From my understanding, this PR does 6 things:
1. Apply pep8 on the code (fix indentation, reorder imports, line size...)
2. Add some missing files for this open-source project (license, contributing guidelines, ...)
3. Add fields `created` and `modified` to the `LockToken` models, via the `django-model-utils` dependency
4. Use `django-braces` for API views
5. Add a structured doc
6. Add support for Django 1.10

Here are some first thoughts on each of those 6 points:

1. Great work, thanks! Nice to have added the `.editorconfig` file. Will be happy to merge.

2. I agree the project needs a license, contributing guidelines, authors list, and other basic files. However if you don't mind I might edit some of them before merging to make them lighter. I might also not keep all of them.

3. I don't really see the point here. 
First of all, it adds a dependency to the package, which I try to avoid at most to keep it light and easy to install. 
Then, depending on `django-model-utils` makes the package lose its compatibility with `Django 1.7`, which is currently supported (and which I need in one of my projects actually :) ).
This makes a lot of unpleasant consequences just to add those two fields to the `LockToken` model, which don't seem useful to me. By the way, in a normal use of the package, the field `modified` will be an exact duplicate of the field `locked_at`, as the token is only modified when it is renewed.

4. Again, I try to avoid at most external dependencies to keep package light and easy to install. I chose not to use any external package to build the API views, as it is very simple and will most likely stay so. The API usage is not even required when using `django-lock-tokens`.
But I'm open to discussion if you think it really brings something!

5. Thanks for the documentation setup! Will be glad to merge.

6. I will merge the new `lock_tokens/app.py` file, thanks.

**Comment by juliomrqz** [comment]
2. Perfect. Some of that files could be improved a little bit. Take a look at the [recommended community standards](https://opensource.guide/), it's a great guide for OpenSource projects.

3. Currently, **Django 1.7** is no longer supported [https://www.djangoproject.com/download/#supported-versions](https://www.djangoproject.com/download/#supported-versions) but It can be supported whenever is need it. I agree with the reason you gave for the modified field :), there is no reason to keep it.

The usefulness of the created field is that you can limit the creation of new tokens based on a elapsed period of time (we need it for a project we're working on :)). For example, it can be done something like this:

```python
if (token.locked_at - token.created) > SELFISH_TIMEOUT:
    raise Warning("You've been editing the file for a long time, others may need it.")
```

If you agree adding the created field, *django-model-utils* can be droped, and we just can do:

```python
class LockToken(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    
    ...
```

---

If you try to avoid at most external dependencies, let's keep it that way. It a good thing not to deviate from the initial conditions of a project, and in this case, the external dependencies do not add significant value.

**Comment by juliomrqz** [comment]
@rparent I crated another pull request with **Less invasive changes**, it could be a good start for adding new features or keeping the existing ones: [Less invasive Improvements ](https://github.com/rparent/django-lock-tokens/pull/3)

**Comment by rparent** [comment]
Ok I get it. That is indeed a useful indication, the example you give could even become a feature from the package.

So if you agree, let's do this:
- Remove `django-model-utils` and `django-braces` dependencies
- Add the `created` field to the `LockToken` model
- Merge

**Comment by juliomrqz** [comment]
Perfect, I'm adding the created field in the last pull I just created

**Comment by rparent** [comment]
Just saw your last comment, ok let's move to this new PR.

**Pull request closed without merging**
